#pragma once

#include <furi.h>
#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/widget.h>
#include <gui/modules/submenu.h>
#include <gui/modules/loading.h>
#include <gui/modules/variable_item_list.h>
#include <gui/modules/text_input.h>

/* generated by fbt from .png files in images folder */
#include <loratalk_icons.h>

#include "loratalk_custom_event.h"
#include "scenes/loratalk_scene.h"

typedef enum {
    LoRaTalkView_Loading,
    LoRaTalkView_MainMenu,
    LoRaTalkView_Config,
    LoRaTalkView_Config_Address,
    LoRaTalkView_Config_Frequency,
    LoRaTalkViewCount,
} LoRaTalkView;

typedef enum {
    BaudRate_300,
    BaudRate_1200,
    BaudRate_4800,
    BaudRate_9600,
    BaudRate_19200,
    BaudRate_28800,
    BaudRate_38400,
    BaudRate_57600,
    BaudRate_115200,
} BaudRate;

typedef enum {
    Bandwidth_125KHz,
    Bandwidth_250KHz,
    Bandwidth_500KHz,
} Bandwidth;

typedef enum {
    CodingRate_4_5,
    CodingRate_4_6,
    CodingRate_4_7,
    CodingRate_4_8,
} CodingRate;

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Loading* loading;
    Submenu* main_menu;
    VariableItemList* config;
    TextInput* config_address;

    uint16_t address;
    BaudRate baud_rate;
} LoRaTalkApp;
