#include <furi.h>
#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/widget.h>
#include <gui/modules/menu.h>
#include <gui/modules/submenu.h>
#include <gui/modules/variable_item_list.h>
#include <gui/modules/text_input.h>

/* generated by fbt from .png files in images folder */
#include <loratalk_icons.h>

typedef enum {
    LoRaTalkScene_MainMenu,
    LoRaTalkScene_Config,
    LoRaTalkScene_Chat,
    LoRaTalkSceneCount
} LoRaTalkScene;

typedef enum {
    LoRaTalkView_MainMenu,
    LoRaTalkView_Config,
    LoRaTalkViewCount,
} LoRaTalkView;

typedef enum {
    BaudRate_300,
    BaudRate_1200,
    BaudRate_2400,
    BaudRate_4800,
    BaudRate_9600,
    BaudRate_19200,
    BaudRate_38400,
    BaudRate_57600,
    BaudRate_115200,
} BaudRate;
const char* baud_rates[] =
    {"300", "1200", "2400", "4800", "9600", "19200", "38400", "57600", "115200"};

typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* main_menu;
    VariableItemList* config_view;

    BaudRate baud_rate;
} LoRaTalkApp;

typedef enum {
    LoRaTalkEvent_ShowConfig,
    LoRaTalkEvent_ShowChat,
} LoRaTalkEvent;

typedef enum {
    MainMenuIndexConfig,
    MainMenuIndexChat,
} MainMenuIndex;

void loratalk_app_menu_callback_main_menu(void* context, uint32_t index) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    switch(index) {
    case MainMenuIndexConfig:
        scene_manager_handle_custom_event(app->scene_manager, LoRaTalkEvent_ShowConfig);
        break;
    case MainMenuIndexChat:
        scene_manager_handle_custom_event(app->scene_manager, LoRaTalkEvent_ShowChat);
        break;
    }
}

void loratalk_app_scene_on_enter_main_menu(void* context) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    menu_reset(app->main_menu);

    menu_add_item(
        app->main_menu,
        "Configure Module",
        NULL,
        MainMenuIndexConfig,
        loratalk_app_menu_callback_main_menu,
        app);
    menu_add_item(
        app->main_menu, "Chat", NULL, MainMenuIndexChat, loratalk_app_menu_callback_main_menu, app);
    view_dispatcher_switch_to_view(app->view_dispatcher, LoRaTalkView_MainMenu);
}

bool loratalk_app_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case LoRaTalkEvent_ShowConfig:
            scene_manager_next_scene(app->scene_manager, LoRaTalkScene_Config);
            consumed = true;
            break;
        case LoRaTalkEvent_ShowChat:
            scene_manager_next_scene(app->scene_manager, LoRaTalkScene_Chat);
            consumed = true;
            break;
        }
        break;
    default:
        consumed = false;
        break;
    }
    return consumed;
}

void loratalk_app_scene_on_exit_main_menu(void* context) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    menu_reset(app->main_menu);
}

void baud_rate_change_callback(VariableItem* item) {
    LoRaTalkApp* app = variable_item_get_context(item);
    uint8_t index = variable_item_get_current_value_index(item);
    variable_item_set_current_value_text(item, baud_rates[index]);
    app->baud_rate = atoi(baud_rates[index]);
}

void loratalk_app_scene_on_enter_config(void* context) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    variable_item_list_reset(app->config_view);

    VariableItem* baud_rate_item = variable_item_list_add(
        app->config_view, "Baud Rate", COUNT_OF(baud_rates), baud_rate_change_callback, app);

    variable_item_set_current_value_index(baud_rate_item, app->baud_rate);
    variable_item_set_current_value_text(baud_rate_item, baud_rates[app->baud_rate]);

    view_dispatcher_switch_to_view(app->view_dispatcher, LoRaTalkView_Config);
}

bool loratalk_app_scene_on_event_config(void* context, SceneManagerEvent event) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case LoRaTalkEvent_ShowConfig:
            scene_manager_next_scene(app->scene_manager, LoRaTalkScene_Config);
            consumed = true;
            break;
        case LoRaTalkEvent_ShowChat:
            scene_manager_next_scene(app->scene_manager, LoRaTalkScene_Chat);
            consumed = true;
            break;
        }
        break;
    default:
        consumed = false;
        break;
    }
    return consumed;
}

void loratalk_app_scene_on_exit_config(void* context) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    variable_item_list_reset(app->config_view);
}

void (*const loratalk_app_scene_on_enter_handlers[])(void*) = {
    loratalk_app_scene_on_enter_main_menu,
    loratalk_app_scene_on_enter_config,
    //loratalk_app_scene_on_enter_chat,
};

bool (*const loratalk_app_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    loratalk_app_scene_on_event_main_menu,
    loratalk_app_scene_on_event_config,
    //loratalk_app_scene_on_event_chat,
};

void (*const loratalk_app_scene_on_exit_handlers[])(void*) = {
    loratalk_app_scene_on_exit_main_menu,
    loratalk_app_scene_on_exit_config,
    //loratalk_app_scene_on_exit_chat,
};

const SceneManagerHandlers loratalk_app_scene_event_handlers = {
    .on_enter_handlers = loratalk_app_scene_on_enter_handlers,
    .on_event_handlers = loratalk_app_scene_on_event_handlers,
    .on_exit_handlers = loratalk_app_scene_on_exit_handlers,
    .scene_num = LoRaTalkSceneCount};

bool loratalk_app_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

bool loratalk_app_scene_manager_navigation_event_callback(void* context) {
    furi_assert(context);
    LoRaTalkApp* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

void loratalk_app_scene_manager_init(LoRaTalkApp* app) {
    app->scene_manager = scene_manager_alloc(&loratalk_app_scene_event_handlers, app);
}

void loratalk_app_view_dispatcher_init(LoRaTalkApp* app) {
    app->view_dispatcher = view_dispatcher_alloc();

    app->main_menu = menu_alloc();
    app->config_view = variable_item_list_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, loratalk_app_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, loratalk_app_scene_manager_navigation_event_callback);

    view_dispatcher_add_view(
        app->view_dispatcher, LoRaTalkView_MainMenu, menu_get_view(app->main_menu));
    view_dispatcher_add_view(
        app->view_dispatcher, LoRaTalkView_Config, variable_item_list_get_view(app->config_view));
}

LoRaTalkApp* loratalk_app_init() {
    LoRaTalkApp* app = malloc(sizeof(LoRaTalkApp));
    loratalk_app_scene_manager_init(app);
    loratalk_app_view_dispatcher_init(app);

    app->baud_rate = BaudRate_9600;

    return app;
}

void loratalk_app_free(LoRaTalkApp* app) {
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, LoRaTalkView_MainMenu);
    view_dispatcher_remove_view(app->view_dispatcher, LoRaTalkView_Config);
    view_dispatcher_free(app->view_dispatcher);
    menu_free(app->main_menu);
    variable_item_list_free(app->config_view);
    free(app);
}

int32_t loratalk_app(void* arg) {
    UNUSED(arg);

    LoRaTalkApp* app = loratalk_app_init();

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, LoRaTalkScene_MainMenu);
    view_dispatcher_run(app->view_dispatcher);

    furi_record_close(RECORD_GUI);
    loratalk_app_free(app);

    return 0;
}
